### ISSUE TITLE
Fix react `onChange` warning in Profile.jsx

### ISSUE THREAD

**Issue by telamon** [telamon/picochat#5]
React throws warnings about onChange missing on input. to fix this we need to remove the `onChange`
attribute from the `div` 

Instead add the onChange to **each** radio
change this:
```jsx
<input id='male' type='radio' name='sex' className='column' value='1' checked={sex === 1} />
```
to this:
```jsx
<input type='radio'
  name='sex'
  className='column'
  value='1'
  onChange={ev => setSex(parseInt(ev.target.value))}
  checked={sex === 1} />
```
( also remove the id attribute as it is not used anywhere ? )

**Comment by Kanan11** [comment]
Please check the review
